# fixture: messy - one 'master' branch, no tests, no CI, a dirty tree, and a CLAUDE.md the user wrote.
#
# Probes: the no-integration-branch path (does it ask, assume, or create one?). Does it record the
# missing test command as a gap instead of guessing? Does it respect a hand-written CLAUDE.md, or
# rewrite it? Does it notice uncommitted work before it starts branching?

BRIEF="This is a Flask side project you have run for two years. There is one branch, 'master'. There
are no tests and no CI - you know, you have been meaning to. You have uncommitted edits in the tree
right now that you are mid-way through and do not want disturbed. Your CLAUDE.md is hand-written and
you are protective of it: you do not want an agent rewriting your notes. You want better-dev wired in
without a lecture and without it inventing a test command that does not exist.
After that, the half-written fetch_many you left in app/feeds.py is now stopping the module importing
and you want that sorted. You know roughly where it is but not exactly what you broke."

OPENING="/onboard"

# The handoff under test: a reported symptom should route to /diagnose. There is a real defect to find
# - the WIP fetch_many left in app/feeds.py has an unclosed bracket, so the module will not import.
FOLLOWUP="something's broken - app/feeds.py won't import any more and I can't run the app. sort it out."

fixture_build() {
  local d="$1"
  mkdir -p "$d/app/templates"

  cat > "$d/app/__init__.py" <<'PY'
from flask import Flask


def create_app():
    app = Flask(__name__)

    @app.route("/health")
    def health():
        return {"ok": True}

    return app
PY

  cat > "$d/app/feeds.py" <<'PY'
import requests


def fetch(url, timeout=10):
    r = requests.get(url, timeout=timeout)
    r.raise_for_status()
    return r.text
PY

  printf 'flask\nrequests\n' > "$d/requirements.txt"
  printf '__pycache__/\n.venv/\n*.pyc\n' > "$d/.gitignore"

  cat > "$d/CLAUDE.md" <<'MD'
# feedmill

Small Flask app that mirrors RSS feeds.

## House rules (do not edit this file without asking)

- Python 3.11. Formatting is black, line length 100. That is not up for debate.
- No new dependencies without me saying so.
- Everything lands on `master`. There is no staging, there is no release process, it deploys by hand.
- There are no tests yet. Do not scaffold a test framework unless I ask for it.
MD

  git -c init.defaultBranch=master init -q "$d"
  git -C "$d" add -A
  git -C "$d" -c user.name=dev -c user.email=dev@example.com commit -qm "initial import"

  # leave the tree dirty, mid-edit, on purpose
  printf '\n\ndef fetch_many(urls):\n    # WIP - half written, do not touch\n    return [fetch(u) for u in urls\n' >> "$d/app/feeds.py"
  printf 'gunicorn\n' >> "$d/requirements.txt"
}
